problem_2/subscribe_and_win/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  root 'subscribers#new'

  get 'admin/dashbord'

  resources :subscribers, only: %i[new create] do
    member do
      get :check_prize
    end
  end
  resources :prizes
  resources :conditions
end

problem_2/subscribe_and_win/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

problem_2/subscribe_and_win/app/models/condition.rb
class Condition < ApplicationRecord
  has_many :prizes

  def self.get_applicable_prizes(subscriber)
    prizes = []
    @subscriber = subscriber
    Condition.all.each do |condition|
      rule = condition.decision_params['rule']
      prizes << if rule == '='
                  condition.prizes.available_items if condition.check_equal?
                elsif rule == '%'
                  condition.prizes.available_items if condition.check_multiple?
                elsif rule == '<'
                  condition.prizes.available_items if condition.check_grater_than?
                elsif rule == '>'
                  condition.prizes.available_items if condition.check_less_than?
                end
          end
    prizes.flatten.compact
  end

  def check_equal?
    decision_params['value'].to_i == @subscriber.id
  end

  def check_multiple?
    (@subscriber.id % decision_params["value"].to_i).zero?
  end

  def check_grater_than?
    @subscriber.id > decision_params["value"].to_i
  end

  def check_less_than?
    @subscriber.id < decision_params["value"].to_i
  end

end

problem_2/subscribe_and_win/app/models/prize.rb
class Prize < ApplicationRecord
  scope :available_items, -> { where('stock_count > 0 ') }

  validates :name, presence: true
  validates :stock_count, presence: true, numericality: true
  belongs_to :condition

  def reduce_count
    self.stock_count -= 1
    save
  end
end

problem_2/subscribe_and_win/app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_uniqueness_of :email, scope: :created_on, message: "You're already subscribed! for this day"

  def select_prizes
    applicable_prize = Condition.get_applicable_prizes(self)
    applicable_prize.each(&:reduce_count)
  end
end

problem_2/subscribe_and_win/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashbord; end
end

problem_2/subscribe_and_win/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

problem_2/subscribe_and_win/app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition,only:[:destroy]
  def new
    @condition = Condition.new
  end

  def index
    @conditions = Condition.all
  end

  def create
    condition = Condition.new(condition_params)
    condition.save
    flash[:success] = 'Successfully Subscribed'
    redirect_to conditions_path
  end

  def destroy
    @condition.destroy
    flash[:success] = 'Successfully deleted'
    redirect_to conditions_path
  end

  private

  def condition_params
    params.require(:condition).permit(:name, decision_params: %i[rule value end start])
  end

  def set_condition
    @condition ||= Condition.find(params[:id])
  end

end

problem_2/subscribe_and_win/app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  before_action :set_prize, only: %i[show edit update destroy]

  def index
    @prizes = Prize.all
  end

  def new
    @conditions = Condition.all
    @prize = Prize.new
  end

  def create
    @prize = Prize.new(prize_params)
    if @prize.save
      redirect_to prize_path(@prize)
      flash[:success] = 'Successfully Created Prize'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @prize.update(prize_params)
      redirect_to prize_path(@prize)
      flash[:success] = 'Successfully Updated Prize'
    else
      render 'edit'
    end
  end

  def destroy
    if @prize.destroy
      redirect_to prizes_path
      flash[:success] = 'Successfully deleted Prize items'
    else
      flash[:error] = 'Error in deleting Prize'
      render 'show'
    end
  end

  private

  def set_prize
    @prize = Prize.includes(:condition).find_by_id(params[:id])
  end

  def prize_params
    params.require(:prize).permit(:stock_count, :name, :condition_id)
  end
end

problem_2/subscribe_and_win/app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to check_prize_subscriber_path(@subscriber)
      flash[:success] = 'Successfully Subscribed'
    else
      render 'new'
    end
  end

  def check_prize
    @subscriber = Subscriber.find(params[:id])
    @prize_list = @subscriber.select_prizes
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email).merge(created_on: Date.today)
    end
  end

problem_2/subscribe_and_win/app/helpers/admin_helper.rb
module AdminHelper
end

problem_2/subscribe_and_win/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :success then 'alert-success'
    when :error then 'alert-danger'
    when :notice then 'alert-info'
    end
  end
end

problem_2/subscribe_and_win/app/helpers/conditions_helper.rb
module ConditionsHelper

	BASIC_RULES = {
		"Equal": "=",
		"Grater Than": ">",
		"Less Than": "<",
		"Multipile of": "%"
	}


	def rule_select_box
		select_tag("condition[decision_params][rule]" ,options_for_select(BASIC_RULES),class: "form-control")
	end

end

problem_2/subscribe_and_win/app/helpers/form_helper.rb
module FormHelper
  def error_message(form, feild)
    if form.object.errors[feild].present?
      error_messsage =  form.object.errors[feild].try(:first).to_s
      content_tag(:div, error_messsage, class: 'alert alert-danger')
    end
 end
end

problem_2/subscribe_and_win/app/helpers/prizes_helper.rb
module PrizesHelper
end

problem_2/subscribe_and_win/app/helpers/subscribers_helper.rb
module SubscribersHelper
end

problem_2/subscribe_and_win/app/views/admin/dashbord.html.erb
<h1>Admin Dashbord</h1>

<nav>
	<ul class="nav nav-pills">
		<li role="presentation right" class="active"> 
			<%=link_to "Prize list", prizes_path %>
		 </li>
		 <li role="presentation right" class="active"> 
		 	<%=link_to "List Prize conditions", conditions_path %>
		 </li>

	</ul>
</nav>

problem_2/subscribe_and_win/app/views/conditions/index.html.erb
<%=link_to "Create conditions", new_condition_path %>

<ul class="list-group">
	<% @conditions.each do |condition|%>
		<li class="list-group-item">
			<%= condition.name%> <%= link_to "Delete" , condition_path(condition), method: :delete, style: "float: right" %>
		</li>
	<%end%>
</ul>

problem_2/subscribe_and_win/app/views/conditions/new.html.erb
<h1>Create Conditions</h1>
<div class="panel panel-default">
	<div class="panel-body">
		<%= form_for @condition do |f| %>
			<div class="form-group">
				<label for="formGroupExampleInput">
					Condition Name : 
				</label>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="form-group">
				<label for="formGroupExampleInput">
					SeleBasic rule
				</label>
				<%= rule_select_box %>
			</div>
			<div class="form-group">
				<label for="formGroupExampleInput"> Enter the params</label>
				<%= number_field_tag "condition[decision_params][value]", class: "form-control" , min: '1' %>
			</div>

			<div class="form-group">
				<label for="formGroupExampleInput"> Range Min</label>
					<%= number_field_tag "condition[decision_params][start]", class: "form-control" , min: '1' %>
				<label for="formGroupExampleInput">    Range Max</label>
					<%= number_field_tag "condition[decision_params][end]", class: "form-control" , min: '1' %>
			</div>

			<div class="form-group">
				<%= f.submit "Create", class: "btn btn-primary"%>
			</div>

		<%end%>
	</div>
</div>

problem_2/subscribe_and_win/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SubscribeAndWin</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav >
		<ul class="nav nav-pills">
			<li role="presentation right" class="active"> 
				<%=link_to "Home", root_path %>
			</li>

			<li role="presentation right" class="active"> 
				<%=link_to "Admin", admin_dashbord_path %>
			</li>
		</ul>
	</nav>

	<div class="container" style="margin-top:150px">
		<% flash.each do |key, value| %>
		<div class="alert <%= flash_class(key) %> " role="alert"><%= value %></div>
		<% end %>
		<%= yield %>
	</body>

	</html>

problem_2/subscribe_and_win/app/views/prizes/_form.html.erb
<%= form_for prize do |form| %>
  Prize Name: <%= form.text_field :name %><br />
   <%= error_message form,:email%>
    Prize Count: <%= form.number_field :stock_count %><br />
    Associates Condition :  <%=form.select :condition_id,options_from_collection_for_select(Condition.all,:id,:name) %>
  <%= form.submit %>
<% end %>

problem_2/subscribe_and_win/app/views/prizes/edit.html.erb
<h1>Prize</h1>


<%= render 'form', prize: @prize %>

<br/>

<%= link_to 'Back', prizes_path %>

problem_2/subscribe_and_win/app/views/prizes/index.html.erb
<h1>Prize List</h1>

<%= link_to "Create New Prize", new_prize_path %>
<ul class="list-group">
	<% @prizes.each do |prize|%>
		<li class="list-group-item">
			<%= link_to prize.name, prize_path(prize) %>
			<span class="badge">
				<%= prize.stock_count %>
			</span>
		</li>
	<%end%>
</ul>

problem_2/subscribe_and_win/app/views/prizes/new.html.erb
<h1>Prize</h1>
<%= render 'form', prize: @prize %>

<br/>

<%= link_to 'Back', prizes_path %>

problem_2/subscribe_and_win/app/views/prizes/show.html.erb
<h1>Prize</h1>


Name : <%=@prize.name %>
<br/>
Count : <%=@prize.stock_count%>
<br/>
Associated Condition name : <%=@prize.condition.name%>
<br/>
<%= link_to 'View all prizes ', prizes_path %>
<%= link_to "Edit", edit_prize_path(@prize)%>

problem_2/subscribe_and_win/app/views/subscribers/check_prize.html.erb
<p><b> Checkout Prize</b> </p>
<ul class="list-group">
	<% @prize_list.each do |prize| %>
		<li class="list-group-item"> <%= prize.name %> </li>
	<%end%>
</ul>

problem_2/subscribe_and_win/app/views/subscribers/new.html.erb
<h1>Subscribe Here</h1>


<div class="container">
	<div class="row">
		<div class="span12">
			<div class="thumbnail center well well-small text-center">
				<h2></h2>
				<p>Subscribe to our prize and stay tuned.</p>
				<div class="input-group input-group-lg">
					<span class="input-group-addon" id="sizing-addon1">@</span>
					<%= form_for @subscriber do |form| %>
					<%= form.text_field :email,placeholder: "your@email.com",class: "form-control" %>
					<%= error_message form,:email%>
				</div>
				<%= form.submit class: "btn btn-info" %>
				<% end %>
			</div>
		</div>
	</div>
</div>